version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4569:4569'
      - '4572:4572'
      - '4575:4575'
      - '4576:4576'
  app:
    build: .
    command: ["./wait-for-it.sh", "localstack:4569", "--", "go", "run", "server.go", "-environment=production"]
    volumes:
      - .:/go/src/github.com/andream16/aws-sdk-go-bindings
    depends_on:
      - localstack
    links:
      - localstack