tasks:
  install-dependencies:
    name: Install dependencies
    command: go mod download
    triggeredBy:
      - postDevcontainerStart

  test:
    name: Test
    command: go test -v -cover -race ./...
    triggeredBy:
      - manual
