tasks:
  install:
    name: Install dependencies
    command: go mod download
    triggeredBy:
      - postDevcontainerStart
  test:
    name: Run tests
    command: go test ./...
    dependsOn:
      - install
    triggeredBy:
      - manual
